version: 2.1

# Define jobs to be invoked in a workflow
jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  sonarqube:
    docker:
      - image: sonarsource/sonar-scanner-cli
    resource_class: small
    working_directory: ~/build
    steps:
      - run:
          name: Install find command
          command: |
            # Check for `apt-get` package manager and install findutils
            if command -v apt-get >/dev/null; then
              apt-get update && apt-get install -y findutils
            else
              echo "Unsupported package manager or OS. Please verify the image."
              exit 1
            fi
      - run:
          name: Find current directory
          command: find .
      - attach_workspace:
          at: ~/workspace
      - run:
          name: SonarQube Analysis
          command: |
            SONAR_BRANCH="${CIRCLE_BRANCH:-master}"
            echo "Sonar branch value is: $SONAR_BRANCH"
            echo "Sonar org value is: $SONAR_ORG"
            sonar-scanner \
              -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
              -Dsonar.organization="$SONAR_ORG" \
              -Dsonar.host.url="https://sonarcloud.io" \
              -Dsonar.exclusions="**/android/**,**/ios/**" \
              -Dsonar.login="$SONAR_TOKEN" \
              -Dsonar.branch.name="$SONAR_BRANCH" \
              -Dsonar.sources="."

# Orchestrate jobs using workflows
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - sonarqube
